config/routes.rb
TplLeaveTool::Application.routes.draw do
  resources :users

  resources :users
  resources :leave_requests
  resources :user_roles
  resources :position_types
  resources :leave_types
  resource :session

  root to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/create_request', to: 'leave_requests#new'

  match '/access_denied', to: 'sessions#access_denied'

end

app/models/leave_request.rb
class LeaveRequest < ActiveRecord::Base
  attr_accessible :comment, :request_status_id, :leave_from, :leave_to,
  				 :leave_type_id, :user_approve_id, :user_request_id

  belongs_to :request_status, class_name: "RequestStatus"
  belongs_to :leave_type
  belongs_to :user_request, class_name: "User", :foreign_key => "user_request_id"
  belongs_to :user_approve, class_name: "User"

  validates :leave_from, :leave_to, :leave_type_id,
  			:user_approve_id, :user_request_id, presence: true

  scope :order_by_created_day, order: 'leave_requests.created_at DESC'
  before_save :init_request_status

  private
  	def init_request_status
  		#pendding status
  		self.request_status_id = 1
  	end

end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :ensure_admin_signed_in, only: [:index, :destroy]
  # GET /leave_requests
  # GET /leave_requests.json
  def index
    @leave_requests = LeaveRequest.order_by_created_day
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leave_requests }
    end
  end

  # GET /leave_requests/1
  # GET /leave_requests/1.json
  def show
    @leave_request = LeaveRequest.find(params[:id])
    if !current_user.admin? && current_user.id != @leave_request.user_request_id
      redirect_to_access_denied_path
    end
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @leave_request }
    # end
  end

  # GET /leave_requests/new
  # GET /leave_requests/new.json
  def new
    @leave_request = LeaveRequest.new
     @leave_types = LeaveType.all
    #User Managers
    @managers = User.where('user_role_id = ?', 2)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leave_request }
    end
  end

  # GET /leave_requests/1/edit
  def edit
    @leave_request = LeaveRequest.find(params[:id])
    @leave_types = LeaveType.all
    @request_statuses = RequestStatus.all
    unless current_user.admin? || current_user.id == @leave_request.user_approve_id
      redirect_to_access_denied_path
    end
  end

  # POST /leave_requests
  # POST /leave_requests.json
  def create
    @leave_request = current_user.leave_requests.build(params[:leave_request])
    # respond_to do |format|
      if @leave_request.save
        # format.html { redirect_to @leave_request, notice: 'Leave request was successfully created.' }
        # format.json { render json: @leave_request, status: :created, location: @leave_request }
        LeaveToolNotifier.request_created(@leave_request).deliver
        flash[:success] = "Leave request was successfully created and sent to your manager"
        redirect_to current_user
      else
        flash[:errors] = @leave_request.errors.full_messages
         redirect_to current_user
        # format.html { render action: "new" }
        # format.json { render json: @leave_request.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PUT /leave_requests/1
  # PUT /leave_requests/1.json
  def update
    @leave_request = LeaveRequest.find(params[:id])

    respond_to do |format|
      if @leave_request.update_attributes(params[:leave_request])
        format.html { redirect_to @leave_request, notice: 'Leave request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leave_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_requests/1
  # DELETE /leave_requests/1.json
  def destroy
    @leave_request = LeaveRequest.find(params[:id])
    @leave_request.destroy

    respond_to do |format|
      format.html { redirect_to leave_requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/leave_requests/_form.html.erb
<div class="row" style="width:100%">
  <div style="width:100%">
    <%= form_for(@leave_request) do |f| %>
      <%= render 'form_basic_user_info' %>
      <table style="width:100%" border="10" bordercolor="brown">
        <tr>
          <td colspan="2" class="sub_header">Leaving Request Details</td>
        </tr>
        <tr>
          <td class="row_leave_left">Reason    :</td>
          <td>
            <%= f.select :leave_type_id, options_from_collection_for_select(@leave_types, 'id', 'name', nil),
             {:include_blank => true}, {:style => "width:30%"} %>
          </td>
        </tr>
         <tr rowspan="2">
          <td class="row_leave_left">Reason text    :<br/>(send to your manager)</td>
          <td>
            <%= f.text_area :comment, :style => "width:60%;height:300px;" %>
          </td>
        </tr>
         <tr>
          <td class="row_leave_left">Leave from    :</td>
          <td>
             <%= f.datetime_select :leave_from, {:style => "width:30px"} %>
          </td>
        </tr>
        <tr>
          <td class="row_leave_left">Leave to    :</td>
          <td>
            <%= f.datetime_select :leave_to %>
          </td>
        </tr>
        <tr>
          <td class="row_leave_left">Leave days   :</td>
          <td>
            asdfsdf
          </td>
        </tr>
        <tr>
          <td colspan="2" class="sub_header">Leave Control</td>
        </tr>
        <tr>
          <td class="row_leave_left">Select your managers    :</td>
          <td>
            <%= f.select :user_approve_id, options_from_collection_for_select(@managers, 'id', 'full_name',nil),
            { :include_blank => true }, {:style => "width:30%"} %>
          </td>
        </tr>
      </table>
        <tr>
          <td colspan="2" class="sub_header" style="align:center;text-align: center;">
            <%= f.submit "submit", class: "btn btn-large btn-primary"%>
          </td>
        </tr>
    <% end %>
  </div>
</div>

app/views/leave_requests/_form_basic_user_info.html.haml
%table{:style => "width:100%", :border => "10", :bordercolor => "gray"}
  %tr
    %th.main_header{:colspan => "2"} New Leave Application
  %tr
    %td.sub_header{:colspan => "2"}Employ Details
  %tr
    %td.row_leave_left Applicant's name    :
    %td.row_leave_right= current_user.full_name
  %tr
    %td.row_leave_left Position    :
    %td.row_leave_right= current_user.position_type.name
  %tr
    %td.row_leave_left Balance    :
    %td.row_leave_right= current_user.balance

app/views/leave_requests/edit.html.haml
%h1 Editing leave_request
= form_for @leave_request do |f|
	%table{ :style=>"width:100%", :border=>"10", :bordercolor=>"gray" }
		%tr
			%th User request
			%th Created at
			%th Leave from
			%th Leave to
			%th Leave day
			%th Status
		%tr
			%td= @leave_request.user_request.full_name
			%td= @leave_request.created_at
			%td= @leave_request.leave_from
			%td= @leave_request.leave_to
			%td asf
			%td= f.select :request_status_id, options_from_collection_for_select(@request_statuses, 'id', 'name', nil), 
											{:include_blank => true}, {:style => "width:100%"}
	= f.submit "Update"
	
= link_to 'Show', @leave_request 
= link_to 'Back', leave_requests_path

app/views/leave_requests/index.html.haml
%h1 Listing leave_requests
%table{ :style=>"width:100%", :border=>"10", :bordercolor=>"gray" }
  %tr
    %th Created at
    %th Leave type
    %th Comment
    %th Leave from
    %th Leave to
    %th User request
    %th User approve
    %th Status

    - @leave_requests.each do |leave_request|
      %tr
        %td= leave_request.created_at
        %td= leave_request.leave_type.name
        %td= leave_request.comment
        %td= leave_request.leave_from.to_s(:short)
        %td= leave_request.leave_to
        %td= link_to leave_request.user_request.full_name, user_path(leave_request.user_request)
        %td= link_to leave_request.user_approve.full_name, user_path(leave_request.user_approve)
        %td= leave_request.request_status.name
        / %td= link_to 'Show', leave_request
        / %td= link_to 'Edit', edit_leave_request_path(leave_request)
        / %td= link_to 'Destroy', leave_request, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Leave request', new_leave_request_path

app/views/leave_requests/new.html.haml
%h1 New Leaving Request

= render 'form'

= link_to 'Back', leave_requests_path

app/views/leave_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Leave type:</b>
  <%= @leave_request.leave_type_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @leave_request.comment %>
</p>

<p>
  <b>Leave from:</b>
  <%= @leave_request.leave_from %>
</p>

<p>
  <b>Leave to:</b>
  <%= @leave_request.leave_to %>
</p>

<p>
  <b>User request:</b>
  <%= @leave_request.user_request.full_name %>
</p>

<p>
  <b>User approve:</b>
  <%= @leave_request.user_approve.full_name %>
</p>

<p>
  <b>Is approved:</b>
  <%= @leave_request.is_approved %>
</p>


<%= link_to 'Edit', edit_leave_request_path(@leave_request) %> |
<%= link_to 'Back', leave_requests_path %>