config/routes.rb
TplLeaveTool::Application.routes.draw do
  resources :users

  resources :users
  resources :leave_requests
  resources :user_roles
  resources :position_types
  resources :leave_types
  resource :session

  root to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/create_request', to: 'leave_requests#new'

  match '/access_denied', to: 'sessions#access_denied'

end

app/controllers/position_types_controller.rb
class PositionTypesController < ApplicationController
  # GET /position_types
  # GET /position_types.json
  def index
    @position_types = PositionType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @position_types }
    end
  end

  # GET /position_types/1
  # GET /position_types/1.json
  def show
    @position_type = PositionType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position_type }
    end
  end

  # GET /position_types/new
  # GET /position_types/new.json
  def new
    @position_type = PositionType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position_type }
    end
  end

  # GET /position_types/1/edit
  def edit
    @position_type = PositionType.find(params[:id])
  end

  # POST /position_types
  # POST /position_types.json
  def create
    @position_type = PositionType.new(params[:position_type])

    respond_to do |format|
      if @position_type.save
        format.html { redirect_to @position_type, notice: 'Position type was successfully created.' }
        format.json { render json: @position_type, status: :created, location: @position_type }
      else
        format.html { render action: "new" }
        format.json { render json: @position_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /position_types/1
  # PUT /position_types/1.json
  def update
    @position_type = PositionType.find(params[:id])

    respond_to do |format|
      if @position_type.update_attributes(params[:position_type])
        format.html { redirect_to @position_type, notice: 'Position type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /position_types/1
  # DELETE /position_types/1.json
  def destroy
    @position_type = PositionType.find(params[:id])
    @position_type.destroy

    respond_to do |format|
      format.html { redirect_to position_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/position_types_helper.rb
module PositionTypesHelper
end

app/views/position_types/_form.html.erb
<%= form_for(@position_type) do |f| %>
  <% if @position_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position_type.errors.count, "error") %> prohibited this position_type from being saved:</h2>

      <ul>
      <% @position_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/position_types/edit.html.erb
<h1>Editing position_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @position_type %> |
<%= link_to 'Back', position_types_path %>

app/views/position_types/index.html.erb
<h1>Listing position_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @position_types.each do |position_type| %>
  <tr>
    <td><%= position_type.name %></td>
    <td><%= link_to 'Show', position_type %></td>
    <td><%= link_to 'Edit', edit_position_type_path(position_type) %></td>
    <td><%= link_to 'Destroy', position_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position type', new_position_type_path %>

app/views/position_types/new.html.erb
<h1>New position_type</h1>

<%= render 'form' %>

<%= link_to 'Back', position_types_path %>

app/views/position_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @position_type.name %>
</p>


<%= link_to 'Edit', edit_position_type_path(@position_type) %> |
<%= link_to 'Back', position_types_path %>