config/routes.rb
TplLeaveTool::Application.routes.draw do
  resources :users

  resources :users
  resources :leave_requests
  resources :user_roles
  resources :position_types
  resources :leave_types
  resource :session

  root to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/create_request', to: 'leave_requests#new'

  match '/access_denied', to: 'sessions#access_denied'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://google.com.vn/">TPL Leave Tools</a>
    by Cowboys team
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer

app/views/layouts/_form_signed_in.html.erb
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= current_user.full_name %> <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Settings", '#' %></li>
    <% if current_user.admin? %>
      <li class="divider"></li>
      <li><%= link_to "Manage user", users_path %></li>
      <li><%= link_to "Manage Leave Types", leave_types_path %></li>
      <li><%= link_to "Manage Leave Requests", leave_requests_path %></li>
    <% end %>
    
    <li class="divider"></li>
    <li>
      <%= link_to "Sign out", signout_path, method: "delete" %>
    </li>
  </ul>
</li>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Leave tools", root_path, id: "logo" %>
      
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <%= render 'layouts/form_signed_in' %>
            <li><%= link_to "New leave", new_leave_request_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	 <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key,value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>